# 讓 Nixpacks 安裝 fontconfig 與 Noto CJK 字型，避免疊字 SVG 顯示錯誤
[phases.setup]
nixPkgs = ["fontconfig", "noto-fonts", "noto-fonts-cjk-sans"]

[phases.build]
cmds = ["npm ci"]

[phases.start]
cmd = "node auto-news.js"
